apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cli-website
  template:
    metadata:
      labels:
        app: cli-website
    spec:
      containers:
      - image: okteto/node:14
        name: cli-website